project:
  type: website
  resources:
    - language-switch.js

website:
  title: "Károly Pálffy's website"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    
    right:
      - text: "Magyar"
        href: "#"
        
format:
  html:
    theme: cosmo
    include-after-body:
      text: |
        <script src="language-switch.js"></script>
