project:
  type: website
  resources:
    - language-switch.js
  render:
    - "*.qmd"
    - "posts/"
    - "!hu/"

website:
  title: "Károly Pálffy's website"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts
    
    right:
      - text: "Magyar"
        href: "#"
        
format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: darkly
    include-after-body:
      text: |
        <script src="language-switch.js"></script>
